export const CREATE_SERVER = "CREATE_SERVER";
export const GET_SERVER_BY_ID = "GET_SERVER_BY_ID";
export const UPDATE_SERVER = "UPDATE_SERVER";
export const DELETE_SERVER = "DELETE_SERVER";
export const GET_CHANNELS = "GET_CHANNELS";
